Numpy Array Operations

import numpy as np 

In [1]:
import numpy as np 

Slicing


In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Basic slicing",arr[2:4])
print("With stepp", arr[2:7:2])

Basic slicing [3 4]
With stepp [3 5 7]


2d array Slicing


In [8]:
arr_2d= np.array([[1,2,3],
                  [4,5,6]])
print("Specific element :",arr_2d[1,1]) # first row first index element 
print("Entire row:",arr_2d[1])# i want entire row 
print("enitre column",arr_2d[:,2])# all rows but only 2nd col

Specific element : 5
Entire row: [4 5 6]
enitre column [3 6]


Sorting


In [14]:
arr_1d=np.array([1,2,3,46,1,2,4,2,1])
print("Sorted array",np.sort(arr_1d))

#2 d array 
# column wise sorting 
arr_2d=np.array([[1,2],
                 [3,1],
                 [4,5]])
print("Sorting column wise :",np.sort(arr_2d,axis=1))
print("Sorting row wise :",np.sort(arr_2d,axis=0))

Sorted array [ 1  1  1  2  2  2  3  4 46]
Sorting column wise : [[1 2]
 [1 3]
 [4 5]]
Sorting row wise : [[1 1]
 [3 2]
 [4 5]]


Filter

In [17]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers=arr[arr%2==0]
print(even_numbers)

[ 2  4  6  8 10]


Filter as mask 

In [20]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
mask=arr>5 #the mask hold the expression 
print("number greater then 5:  ",arr[mask])

number greater then 5:   [ 6  7  8  9 10]


Fancy indexing vs np.where()

In [24]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
index=[0,2,4]
print("particular index elemenet",arr[index])

where_result=np.where(arr>5)
print("with wehere ",arr[where_result])

particular index elemenet [1 3 5]
with wehere  [ 6  7  8  9 10]


Concatnate two array ( merge two array 
)

In [26]:
arr1= np.array([1,2,3])
arr2=np.array([4,5,6])
print("Combined array ",np.concatenate((arr1,arr2)))

Combined array  [1 2 3 4 5 6]


In [28]:

arr1= np.array([1,2,3])
arr2=np.array([4,5,6,7,8])
print("compatibility of arrays : ",arr1.shape==arr2.shape)

compatibility of arrays :  False


In [34]:
arr=np.array([[1,2],[3,4]])
new_row=np.array([5,6])
new_arr_with_row=np.vstack((arr,new_row))
print(arr)
print(new_arr_with_row)

new_col=np.array(([2],[3]))
new_with_col=np.hstack((arr,new_col))
print(new_with_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 2]
 [3 4 3]]


Deletion on array 

In [37]:
arr=np.array([1,2,3,5,6,7])
arr_after_deletion=np.delete(arr,2)
print(arr_after_deletion)

[1 2 5 6 7]
