## numpy arrray and basics 


import numpy as np


In [3]:
import numpy as np


## Creating array 


In [4]:
arr_1d=np.array([1,2,3,4,5])
print("1 d array",arr_1d)


1 d array [1 2 3 4 5]


2d array


In [5]:
arr_2d= np.array([[1,2,3,4],[5,6,7,8]])
print("2 d array",arr_2d)

2 d array [[1 2 3 4]
 [5 6 7 8]]


Creating Array from scratch 

In [6]:
ones_array = np.array([3,4])
print(ones_array)

[3 4]


In [7]:
ones_array = np.zeros([3,4])
print(ones_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
ones_array=np.ones([2,2])
print(ones_array)

[[1. 1.]
 [1. 1.]]


In [9]:
full_array=np.full((2,2),7)
print(full_array)

[[7 7]
 [7 7]]


In [10]:
random=np.random.random((2,3))
print(random)

[[0.26850215 0.95582269 0.12515469]
 [0.47719451 0.27251518 0.67287955]]


In [11]:
sequence_array=np.arange(1,11)
print(sequence_array)

[ 1  2  3  4  5  6  7  8  9 10]


Vector 

In [12]:
vector = np.array([1,2,3,45])
print("vector",vector)

vector [ 1  2  3 45]


Matrix

In [14]:
matrix = np.array([[1,2,3,4],[5,6,7,8]])
print("matrix",matrix)

matrix [[1 2 3 4]
 [5 6 7 8]]


Tensor

In [16]:
tensor = np.array([[1,2,34],
                   [4,5,6],
                   [3,7,8]])
print(tensor)

[[ 1  2 34]
 [ 4  5  6]
 [ 3  7  8]]


In [18]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape",arr.shape)
print("Dimensions",arr.ndim)
print("Size",arr.size)
print("data type",arr.dtype)

Shape (2, 3)
Dimensions 2
Size 6
data type int64


Array Reshaping 

In [27]:
arr= np.arange(6)
print("Original array ",arr)

reshaped=arr.reshape((2,3))
print("reshaped array ",reshaped)

flatten =reshaped.flatten()
print("Flatten array " , flatten)
#it return view instead of copy 
raveled = reshaped.ravel()
print("ravel array",raveled)

#Transpose matrix 
transpose= reshaped.T
print("transpose of a matrix ",transpose)

Original array  [0 1 2 3 4 5]
reshaped array  [[0 1 2]
 [3 4 5]]
Flatten array  [0 1 2 3 4 5]
ravel array [0 1 2 3 4 5]
transpose of a matrix  [[0 3]
 [1 4]
 [2 5]]
